compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'yes'
gpu_ids: all
mixed_precision: 'bf16'
num_machines: 1
num_processes: 8
main_process_port: 29501
rdzv_backend: static
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false