python src/train_bash.py \
    --stage sft \
    --model_name_or_path ticoAg/gpt2-tigerbot-pt-zh \
    --do_train \
    --finetuning_type full \
    --dataset tiger_sft_zh \
    --template ziya \
    --use_fast_tokenizer \
    --preprocessing_num_workers 8 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --output_dir .cache/gpt2-sft-tigersftzh \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --eval_steps 500 \
    --val_size 0.001 \
    --warmup_ratio 0.1 \
    --save_total_limit 10 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --evaluation_strategy steps \
    --plot_loss \
    --max_source_length 512 \
    --max_target_length 512 \
    --bf16