CUDA_VISIBLE_DEVICES=0 python src/train_sft.py \
    --model_name_or_path YeungNLP/bloomz-6b4-mt-zh \
    --do_train \
    --dataset alpaca-gpt4-zh \
    --finetuning_type lora \
    --output_dir ckpt/bloomz-6b4-mt-zh-alpaca-gpt4-zh \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 2 \
    --plot_loss \
    --resume_lora_training true \
    --lora_target query_key_value,dense,dense_ \
    --use_fast_tokenizer \
    --bf16 \
    --quantization_bit 4